services:
  bot:
    build:
      context: .
      dockerfile: app/bot/Dockerfile
    container_name: luvly_bot
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./model_cache:/root/.cache
  support_bot:
    build:
      context: .
      dockerfile: app/support_bot/Dockerfile
    container_name: luvly_support_bot
    restart: on-failure
    env_file:
      - .env
  db:
    image: ankane/pgvector:latest
    container_name: luvly_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_DB}
      - TZ=Europe/Moscow
    volumes:
      - luvly_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: luvly_redis
    restart: always
    ports:
      - "6380:6379"
  # Воркер Taskiq
  worker:
    build:
        context: .
        dockerfile: app/task_schedule/Dockerfile
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    container_name: taskiq_worker
    command: taskiq worker app.task_schedule.main:broker
    depends_on:
      - redis
      - db
    env_file: .env
  # Планировщик Taskiq
  scheduler:
    build:
        context: .
        dockerfile: app/task_schedule/Dockerfile
    environment:
      - TZ=Europe/Moscow
      - PYTHONUNBUFFERED=1
    container_name: taskiq_scheduler
    command: taskiq scheduler app.task_schedule.main:scheduler
    depends_on:
      - redis
    env_file: .env

volumes:
  luvly_data: