services:
#  bot:
#    build:
#      context: .
#      dockerfile: ./app/bot/Dockerfile
#    container_name: luvly_bot
#    env_file:
#      - .env
##    volumes:
##      - ./app/bot:/app
#    restart: always
  db:
    image: ankane/pgvector:latest
    container_name: luvly_db
    ports:
      - "5433:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_DB=${DB_DB}
      - TZ=Europe/Moscow
    volumes:
      - luvly_data:/var/lib/postgresql/data

volumes:
  luvly_data: