ai:
  base_url: "https://openrouter.ai/api/v1"
  default_model: "nvidia/nemotron-3-nano-30b-a3b:free"
  embedder_model: "paraphrase-multilingual-MiniLM-L12-v2"
  daily_limit: 3000
gar:
  base_url: "https://nominatim.openstreetmap.org/search"
  user_agent: "LuvlyAiBot/1.0"
use_proxy: true