"""fix user_filter age

Revision ID: 569c36572c5d
Revises: ab89c55ce27b
Create Date: 2026-03-29 00:15:37.836988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = '569c36572c5d'
down_revision: Union[str, Sequence[str], None] = 'ab89c55ce27b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_filter', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_filter', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_filter', 'max_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_filter', 'min_age',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
