"""init

Revision ID: fe89347664a6
Revises: 
Create Date: 2026-03-25 03:06:07.966671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'fe89347664a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gar_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio_vector', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('telegram_id')
    )
    op.create_index(op.f('ix_user_profile_gar_city'), 'user_profile', ['gar_city'], unique=False)
    op.create_table('match_action',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_match', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['from_user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('from_user_id', 'to_user_id', name='unique_match_action')
    )
    op.create_index(op.f('ix_match_action_action'), 'match_action', ['action'], unique=False)
    op.create_index(op.f('ix_match_action_from_user_id'), 'match_action', ['from_user_id'], unique=False)
    op.create_index('ix_match_action_to_user', 'match_action', ['to_user_id'], unique=False)
    op.create_index(op.f('ix_match_action_to_user_id'), 'match_action', ['to_user_id'], unique=False)
    op.create_table('user_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('target_gender', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('min_age', sa.Integer(), nullable=False),
    sa.Column('max_age', sa.Integer(), nullable=False),
    sa.Column('target_city', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_unique_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_media_user_id'), 'user_media', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_media_user_id'), table_name='user_media')
    op.drop_table('user_media')
    op.drop_table('user_filter')
    op.drop_index(op.f('ix_match_action_to_user_id'), table_name='match_action')
    op.drop_index('ix_match_action_to_user', table_name='match_action')
    op.drop_index(op.f('ix_match_action_from_user_id'), table_name='match_action')
    op.drop_index(op.f('ix_match_action_action'), table_name='match_action')
    op.drop_table('match_action')
    op.drop_index(op.f('ix_user_profile_gar_city'), table_name='user_profile')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
